image: cirrusci/flutter

pipelines:
  branches:
    main:
      - step:
          name: 'Adding required files'
          script:
            - echo $GOOGLE_SERVICE_JSON | base64 --decode > android/app/google-services.json
            - echo $ENCRYPTION_KEYS | base64 --decode > lib/.dart
      - step:
          name: 'Analyzing the code'
          script: 
            - flutter analyze
  tags:
    v*:
      - step:
          name: 'Getting all dependencies'
          script: 
            - flutter pub get
      - step:
          name: 'Adding required files'
          script:
            - echo $GOOGLE_SERVICE_JSON | base64 --decode > android/app/google-services.json
            - echo $ENCRYPTION_KEYS | base64 --decode > lib/.dart
      - step:
          name: 'Building android applications'
          script:
            - flutter build apk -t lib/main.dart --split-per-abi
            - echo 'Building finished'